api_key = "818cffde0b1e6749199b67fee1cbd032"
movieSearchURL = "https://api.themoviedb.org/3/search/movie?api_key={}".format(api_key)
posterPathURL = "http://image.tmdb.org/t/p/w185{}"
upcomingMovieURL = "https://api.themoviedb.org/3/movie/upcoming?api_key={}".format(api_key)
nowPlayingMovieURL = "https://api.themoviedb.org/3/movie/now_playing?api_key={}".format(api_key)
movieReviewURL = "https://api.themoviedb.org/3/movie/{}/reviews?api_key={}"
popularMovieURL = "https://api.themoviedb.org/3/movie/popular?api_key={}&region={}"
posterPathURL_L = "http://image.tmdb.org/t/p/w342{}"
genreDetailURL = "https://api.themoviedb.org/3/genre/movie/list?api_key={}".format(api_key)
yifyMovieDetailURL = "https://yts.mx/api/v2/list_movies.json?query_term={}"
youtubeTrailerURL = "https://www.youtube.com/watch?v={}"
