api_key = "818cffde0b1e6749199b67fee1cbd032"
movieSearchURL = "https://api.themoviedb.org/3/search/movie?api_key={}".format(api_key)
posterPathURL = "http://image.tmdb.org/t/p/w185{}"
upcomingMovieURL = "https://api.themoviedb.org/3/movie/upcoming?api_key={}".format(api_key)
nowPlayingMovieURL = "https://api.themoviedb.org/3/movie/now_playing?api_key={}".format(api_key)
movieReviewURL = "https://api.themoviedb.org/3/movie/{}/reviews?api_key={}"
popularMovieURL = "https://api.themoviedb.org/3/movie/popular?api_key={}&region={}"
posterPathURL_L = "http://image.tmdb.org/t/p/w342{}"
genreDetailURL = "https://api.themoviedb.org/3/genre/movie/list?api_key={}".format(api_key)
yifyMovieDetailURL = "https://yts.mx/api/v2/list_movies.json?query_term={}"
youtubeTrailerURL = "https://www.youtube.com/embed/{}"
imdb_URL = "https://www.imdb.com/title/{}/"
yifyMovieSearchURL = "https://yts.mx/api/v2/movie_details.json?movie_id={}&with_cast={}&with_images={}"
yifySimilarMovieURL = "https://yts.mx/api/v2/movie_suggestions.json?movie_id={}"
imdbProfileURL = "https://www.imdb.com/name/nm{}"
tmdbMovieDetailsURL = "https://api.themoviedb.org/3/movie/{}?api_key={}&append_to_response=credits"
tmdbPersonDetailsURL = "https://api.themoviedb.org/3/person/{}?api_key={}"
tmdbProfileURL = "https://image.tmdb.org/t/p/original{}"
